#! /bin/bash

if [ -z $2 ] ; then
	echo "Usage: chmodd1 <mode> <path>"
	echo ""
	echo "Allocates the given permissions mode to all directories found"
	echo "in the given directory."
	echo ""
	echo "For more info on modes, see man chmod"
	echo ""
	echo "Author: Daniel Convissor <danielc@analysisandsolutions.com>"
	exit 1
fi

find $2 -maxdepth 1 -type d -exec chmod $1 {} \;
