#! /bin/bash -e

if [[ $1 == "-h" || $1 == "--help" ]] ; then
	echo "Usage:  duh [arguments] [paths]"
	echo ""
	echo "Disk Usage Human makes a size ordered list of dirs in given location"
	echo ""
	echo "Author: Daniel Convissor <danielc@analysisandsolutions.com>"
	exit 1
fi

du --max-depth=1 -B M "$@" | awk '{printf("% 10s %s\n", $1, $2);}' | sort
