#! /bin/bash

if [[ $1 == "-h" || $1 == "--help" ]] ; then
	echo "Usage:  phplss [svn status arguments] [svn status paths]"
	echo ""
	echo "Runs PHP lint on all modified files in the current SVN repository."
	echo ""
	echo "Author: Daniel Convissor <danielc@analysisandsolutions.com>"
	exit 1
fi

for file in $(svn status "$@" | grep -E '^[AM?]' | awk '{print $NF}')
do
	php -l "$file"
done 
