#! /bin/bash

if [[ $1 == "-h" || $1 == "--help" ]] ; then
	echo "Usage:  vgs [arguments] [paths]"
	echo ""
	echo "Opens all modified files in the current Git repository."
	echo ""
	echo "Author: Daniel Convissor <danielc@analysisandsolutions.com>"
	exit 1
fi

vim -p $(git status --porcelain "$@" | grep -vE '^D' | awk '{print $2}')
