#! /bin/bash

if [[ $1 == "-h" || $1 == "--help" ]] ; then
	echo "Usage:  vss [svn status arguments] [svn status paths]"
	echo ""
	echo "Has Vim open all modified files in the current SVN repository."
	echo ""
	echo "Author: Daniel Convissor <danielc@analysisandsolutions.com>"
	exit 1
fi

vim -p $(svn status "$@" | grep -E '^[AM?]' | awk '{print $NF}')
